### ISSUE TITLE
unraid docker启动失败 2.10.0

### ISSUE THREAD

**Issue by ChenMercy** [sgpublic/nas-tools-enhanced#3]
Traceback (most recent call last):
  File "/nas-tools-enhanced/run.py", line 168, in <module>
    init_system()
  File "/nas-tools-enhanced/run.py", line 101, in init_system
    init_data()
  File "/nas-tools-enhanced/app/db/__init__.py", line 26, in init_data
    MainDb().init_data()
  File "/nas-tools-enhanced/app/db/main_db.py", line 60, in init_data
    config['app']['init_files'] = init_files
KeyError: 'app'
Traceback (most recent call last):
  File "/nas-tools-enhanced/run.py", line 168, in <module>
    init_system()
  File "/nas-tools-enhanced/run.py", line 101, in init_system
    init_data()
  File "/nas-tools-enhanced/app/db/__init__.py", line 26, in init_data
    MainDb().init_data()
  File "/nas-tools-enhanced/app/db/main_db.py", line 60, in init_data
    config['app']['init_files'] = init_files
KeyError: 'app'
Traceback (most recent call last):
  File "/nas-tools-enhanced/run.py", line 168, in <module>
    init_system()
  File "/nas-tools-enhanced/run.py", line 101, in init_system
    init_data()
  File "/nas-tools-enhanced/app/db/__init__.py", line 26, in init_data
    MainDb().init_data()
  File "/nas-tools-enhanced/app/db/main_db.py", line 60, in init_data
    config['app']['init_files'] = init_files
KeyError: 'app'
Textual SQL expression 'UPDATE main.CONFIG_USERS ...' should be explicitly declared as text('UPDATE main.CONFIG_USERS ...')
Textual SQL expression 'UPDATE CONFIG_USER_RSS SE...' should be explicitly declared as text('UPDATE CONFIG_USER_RSS SE...')
程序自动升级已关闭，如需自动升级请在创建容器时设置环境变量：NASTOOL_AUTO_UPDATE=true
以PUID=0，PGID=0的身份启动程序...
./start.sh
Installing dependencies from lock file

No dependencies to install or update
【Config】加载 config.yaml 配置出错：[Errno 2] No such file or directory: '/config/config.yaml/../'
NAStool 当前版本号：v2.10.0
开始初始化数据库...
数据库初始化完成
开始更新数据库...
数据库更新完成
开始初始化数据...
Textual SQL expression 'INSERT OR IGNORE INTO "CO...' should be explicitly declared as text('INSERT OR IGNORE INTO "CO...')
Textual SQL expression 'INSERT OR IGNORE INTO "CO...' should be explicitly declared as text('INSERT OR IGNORE INTO "CO...')
Textual SQL expression 'INSERT OR IGNORE INTO "CO...' should be explicitly declared as text('INSERT OR IGNORE INTO "CO...')
Textual SQL expression 'INSERT OR IGNORE INTO "CO...' should be explicitly declared as text('INSERT OR IGNORE INTO "CO...')
Textual SQL expression 'INSERT OR IGNORE INTO "CO...' should be explicitly declared as text('INSERT OR IGNORE INTO "CO...')
Textual SQL expression 'INSERT OR REPLACE INTO "C...' should be explicitly declared as text('INSERT OR REPLACE INTO "C...')
Textual SQL expression 'INSERT OR REPLACE INTO "C...' should be explicitly declared as text('INSERT OR REPLACE INTO "C...')
Textual SQL expression 'INSERT OR REPLACE INTO "C...' should be explicitly declared as text('INSERT OR REPLACE INTO "C...')
Textual SQL expression 'INSERT OR REPLACE INTO "C...' should be explicitly declared as text('INSERT OR REPLACE INTO "C...')
Textual SQL expression 'INSERT OR REPLACE INTO "C...' should be explicitly declared as text('INSERT OR REPLACE INTO "C...')
Textual SQL expression 'delete from alembic_versi...' should be explicitly declared as text('delete from alembic_versi...')
Textual SQL expression 'UPDATE RSS_MOVIES SET DOW...' should be explicitly declared as text('UPDATE RSS_MOVIES SET DOW...')
Textual SQL expression 'UPDATE RSS_TVS SET DOWNLO...' should be explicitly declared as text('UPDATE RSS_TVS SET DOWNLO...')
Textual SQL expression '' should be explicitly declared as text('')
Textual SQL expression 'UPDATE main.CONFIG_USERS ...' should be explicitly declared as text('UPDATE main.CONFIG_USERS ...')
Textual SQL expression 'UPDATE CONFIG_USER_RSS SE...' should be explicitly declared as text('UPDATE CONFIG_USER_RSS SE...')
程序自动升级已关闭，如需自动升级请在创建容器时设置环境变量：NASTOOL_AUTO_UPDATE=true
以PUID=0，PGID=0的身份启动程序...
./start.sh
Installing dependencies from lock file

No dependencies to install or update
【Config】加载 config.yaml 配置出错：[Errno 2] No such file or directory: '/config/config.yaml/../'
NAStool 当前版本号：v2.10.0
开始初始化数据库...
数据库初始化完成
开始更新数据库...
数据库更新完成
开始初始化数据...
Textual SQL expression 'INSERT OR IGNORE INTO "CO...' should be explicitly declared as text('INSERT OR IGNORE INTO "CO...')
Textual SQL expression 'INSERT OR IGNORE INTO "CO...' should be explicitly declared as text('INSERT OR IGNORE INTO "CO...')
Textual SQL expression 'INSERT OR IGNORE INTO "CO...' should be explicitly declared as text('INSERT OR IGNORE INTO "CO...')
Textual SQL expression 'INSERT OR IGNORE INTO "CO...' should be explicitly declared as text('INSERT OR IGNORE INTO "CO...')
Textual SQL expression 'INSERT OR IGNORE INTO "CO...' should be explicitly declared as text('INSERT OR IGNORE INTO "CO...')
Textual SQL expression 'INSERT OR REPLACE INTO "C...' should be explicitly declared as text('INSERT OR REPLACE INTO "C...')
Textual SQL expression 'INSERT OR REPLACE INTO "C...' should be explicitly declared as text('INSERT OR REPLACE INTO "C...')
Textual SQL expression 'INSERT OR REPLACE INTO "C...' should be explicitly declared as text('INSERT OR REPLACE INTO "C...')
Textual SQL expression 'INSERT OR REPLACE INTO "C...' should be explicitly declared as text('INSERT OR REPLACE INTO "C...')
Textual SQL expression 'INSERT OR REPLACE INTO "C...' should be explicitly declared as text('INSERT OR REPLACE INTO "C...')
Textual SQL expression 'delete from alembic_versi...' should be explicitly declared as text('delete from alembic_versi...')
Textual SQL expression 'UPDATE RSS_MOVIES SET DOW...' should be explicitly declared as text('UPDATE RSS_MOVIES SET DOW...')
Textual SQL expression 'UPDATE RSS_TVS SET DOWNLO...' should be explicitly declared as text('UPDATE RSS_TVS SET DOWNLO...')
Textual SQL expression '' should be explicitly declared as text('')
Textual SQL expression 'UPDATE main.CONFIG_USERS ...' should be explicitly declared as text('UPDATE main.CONFIG_USERS ...')
Textual SQL expression 'UPDATE CONFIG_USER_RSS SE...' should be explicitly declared as text('UPDATE CONFIG_USER_RSS SE...')

**Comment by ChenMercy** [comment]
找到原因了，映射目录的时候多写了一个空格。。。。

**Comment by sgpublic** [comment]
解决了哈，解决了就close了
