### ISSUE TITLE
UNRAID创建容器无法启动，提示无法找到config.yaml文件

### ISSUE THREAD

**Issue by genesis-lua** [sgpublic/nas-tools-enhanced#4]
终于有这个版本，创建时发现在config里少了几个文件，需要从原版容器复制过来才能正常启动
![image](https://user-images.githubusercontent.com/26401920/224551779-ea33e0d2-9305-4ac4-b121-184769acf58c.png)

**Comment by genesis-lua** [comment]
另外还发现字幕插件没有正常加载，原版3.0.3的定时同步没有，因为挂载的NAS盘经常同步不到电影，需要手动同步

**Comment by sgpublic** [comment]
关于原版定时同步，此仓库不打算同步官方功能；config 创建失败的问题下版本修。
