### ISSUE TITLE
无法连接xunlei下载器

### ISSUE THREAD

**Issue by ibeange** [sgpublic/nas-tools-enhanced#5]
我使用是cnk3x/xunlei这个docker镜像，但是4321端口一直测试失败，我使用的是host网络，请问我是哪里配置错了吗？

**Comment by sgpublic** [comment]
端口取决于 xunlei 那边配置的端口，如果确定两边端口一致那就是 bug 了

**Comment by ibeange** [comment]
我使用的是--net=host -e XL_WEB_PORT=4321，而且确定可以使用4321端口打开xunlei页面，但是测试一直失败。

**Comment by zhonxinya** [comment]
啥时候修复这个bug啊，有其他替代方案吗

**Comment by sgpublic** [comment]
> 啥时候修复这个bug啊，有其他替代方案吗

已经在 dev 分支尝试修复了，一直没时间测，并且群晖那边还有问题我还不知道该怎么测。

其他解决方案的话我个人目前没有看到其他我觉得不错的
