### ISSUE TITLE
两个问题请教下

### ISSUE THREAD

**Issue by jasonding121205** [sgpublic/nas-tools-enhanced#6]
很好的项目，感谢付出。但使用中有两个问题想请教下：
1.站点浏览器仿真只能选否，是否镜像中没有浏览器？
2.内建索引器选择了所有公开站点，但试了好几个搜索，不知为何一律只有pt站的搜索结果

**Comment by sgpublic** [comment]
1. 我大概知道原因，原因猜没错的话测试后下版本修。
2. 内建索引器我目前只是把站点加回去了，具体能不能用我没测过，建议使用 Jackett。

**Comment by jasonding121205** [comment]
感谢！期待下一版。
